apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.deployment.finished
      requests:
        - url: https://webexapis.com/v1/webhooks/incoming/Y2lzY29zcGFyazovL3VzL1dFQkhPT0svNjU4YTgyYmMtOTBhMC00YTk0LTgzM2QtZmE1YjRjZDU0MzI3
          payload: >-
            {"markdown":"the deployment is finished"}
          headers:
            - key: Content-Type
              value: application/json
          method: POST
      subscriptionID: cbff3ae1-3c8c-4eaf-85ca-a8fd2ac90487
      sendFinished: false
      sendStarted: false
    - type: sh.keptn.event.evaluation.>
      requests:
        - url: https://webexapis.com/v1/webhooks/incoming/Y2lzY29zcGFyazovL3VzL1dFQkhPT0svNjU4YTgyYmMtOTBhMC00YTk0LTgzM2QtZmE1YjRjZDU0MzI3
          payload: >-
            {"markdown":"Evaluation {{.time}} - {{.source}} - {{.type}}"}
          headers:
            - key: Content-Type
              value: application/json
          method: POST
      subscriptionID: 3c089cfb-432f-44ca-9b37-96fe6b6ed13b
      sendFinished: false
      sendStarted: false
    - type: sh.keptn.event.release.>
      requests:
        - url: https://webexapis.com/v1/webhooks/incoming/Y2lzY29zcGFyazovL3VzL1dFQkhPT0svNjU4YTgyYmMtOTBhMC00YTk0LTgzM2QtZmE1YjRjZDU0MzI3
          payload: >-
            {"markdown":"Release {{.time}} - {{.source}} - {{.type}}"}
          headers:
            - key: Content-Type
              value: application/json
          method: POST
      subscriptionID: 52f645a8-23bc-4939-a789-eed52204313f
      sendFinished: false
      sendStarted: false
    - type: sh.keptn.event.test.>
      requests:
        - url: https://webexapis.com/v1/webhooks/incoming/Y2lzY29zcGFyazovL3VzL1dFQkhPT0svNjU4YTgyYmMtOTBhMC00YTk0LTgzM2QtZmE1YjRjZDU0MzI3
          payload: >-
            {"markdown":"Test {{.time}} - {{.source}} - {{.type}}"}
          headers:
            - key: Content-Type
              value: application/json
          method: POST
      subscriptionID: 54eb8af8-e62e-41f1-9ec6-b025e0596df9
      sendFinished: false
      sendStarted: false
    - type: sh.keptn.event.deployment.>
      requests:
        - url: https://webexapis.com/v1/webhooks/incoming/Y2lzY29zcGFyazovL3VzL1dFQkhPT0svNjU4YTgyYmMtOTBhMC00YTk0LTgzM2QtZmE1YjRjZDU0MzI3
          payload: >-
            {"markdown":"Deployment {{.time}} - {{.type}} - {{.data.project}} - {{.data.service}} - {{.data.stage}} - "}
          headers:
            - key: Content-Type
              value: application/json
          method: POST
      subscriptionID: 9db8c9bd-6d40-4a97-909b-24ecd4b098fc
      sendFinished: false
      sendStarted: false
