apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.deployment.finished
      requests:
        - url: https://webexapis.com/v1/webhooks/incoming/Y2lzY29zcGFyazovL3VzL1dFQkhPT0svNjU4YTgyYmMtOTBhMC00YTk0LTgzM2QtZmE1YjRjZDU0MzI3
          payload: >-
            {"markdown":"the deployment is finished"}
          headers:
            - key: Content-Type
              value: application/json
          method: POST
      subscriptionID: cbff3ae1-3c8c-4eaf-85ca-a8fd2ac90487
      sendFinished: false
      sendStarted: false
